# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glew/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glfw/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glfw/cmake_uninstall.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glfw/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glfw/src/glfw3.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glfw/src/glfw3Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/deps/glfw/src/glfw_config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/CGL/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/BasicConfigVersion-SameMajorVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindFreetype.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.25.2/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.25.2/bin/cmake -H/Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui -B/Users/cuiboy/Desktop/code/berkeley/classes/cs184/p2-meshedit-sp23-cs184-proj2-cui/xcode
